process:
  execute: True
  doGithubSearch: True
  doGitlabSearch: True
  usePickleFile: False
  useResultsExcelFile: False
  tmpDirectory: tmp
  tmpFile: /ftmp
github:
  queryFile: github_querys/query2.txt
  filterCommits: False
  MAX_COMMITS: 10000
  MIN_COMMITS: 1000
  randomizeRepos: False
  N_RANDOM: 10
  onlyPositives: False
gitlab:
  #Si buscamos solo positivos, search1By1 será True sí o sí (se controla por programa), da igual lo que venga en el fichero de configuración.
  search1By1: True
  LANGUAGE: ALL
  N_MAX_SEARCHES: 118550
  N_MIN_STARS: 50
  onlyPositives: False
  #Si solo buscamos positivos, N_MAX_PROJECTS será el nº máximo de positivos a encontrar.
  #Si buscamos tanto positivos como negativos, N_MAX_PROJECTS será el número máximo de projectos que tratará (sean o no positivos en CI).
  N_MAX_PROJECTS: 100
