process:
  execute: True
  doGithubSearch: True
  doGitlabSearch: False
  usePickleFile: False
  useResultsExcelFile: False
  tmpDirectory: tmp
  tmpFile: /ftmp
github:
  queryFile: github_querys/query1_2.txt
  filterCommits: False
  MIN_COMMITS: 1000
  MAX_COMMITS: 10000
  randomizeRepos: False
  N_RANDOM: 10
  onlyPositives: True
gitlab:
  #Si buscamos solo positivos, search1By1 será True sí o sí (se controla por programa), da igual lo que venga en el fichero de configuración.
  search1By1: True
  N_ERROR_PAGE_ATTEMPTS: 2
  LANGUAGE: ALL
  N_MAX_SEARCHES: 218550
  N_MIN_STARS: 25
  onlyPositives: True
  #Si solo buscamos positivos, N_MAX_PROJECTS será el nº máximo de positivos a encontrar.
  #Si buscamos tanto positivos como negativos, N_MAX_PROJECTS será el número máximo de projectos que tratará (sean o no positivos en CI).
  N_MAX_PROJECTS: 500
